<?php
/**
 * Pattern content.
 */
return array(
	'title'      => __( 'Gutenverse Home Feature', 'startupzy' ),
	'categories' => array( 'startupzy-gutenverse' ),
	'content'    => '<!-- wp:gutenverse/section {"width":{"Desktop":"1170"},"elementId":"guten-Rthj1H","background":{"type":"default","color":{"r":255,"g":255,"b":255,"a":1}},"margin":{"Tablet":[],"Desktop":[]},"padding":{"Tablet":{"unit":"px","dimension":{"left":"10","right":"10"}},"Desktop":[]},"wrapColumn":{"Desktop":false,"Tablet":false,"Mobile":true}} -->
<!-- wp:gutenverse/column {"width":{"Desktop":100},"elementId":"guten-XTtDqn"} -->
<!-- wp:gutenverse/section {"width":{"Desktop":"1170"},"isChild":true,"gap":"no","elementId":"guten-gnUI0k","margin":{"Desktop":{"unit":"px","dimension":{"top":"-120"}}},"padding":{"Desktop":[]},"wrapColumn":{"Desktop":false,"Tablet":false,"Mobile":true}} -->
<!-- wp:gutenverse/column {"width":{"Desktop":23,"Tablet":50},"elementId":"guten-w4RFxJ","border":{"radius":{"Desktop":[]}},"margin":{"Desktop":[],"Mobile":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"","right":"0","bottom":"","left":""}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"animation":{"type":{"Desktop":"fadeInLeft"},"duration":"normal"}} -->
<!-- wp:gutenverse/icon-box {"elementId":"guten-tNYwfa","title":"Best Service","titleTag":"h3","description":"Lorem ipsum dolor sit amet, consectet adipiscing elit, sed do eiusmod tempor dolor","icon":"fas fa-laptop-code","iconSize":{"Desktop":"40"},"iconPosition":"top","containerPadding":{"Desktop":{"unit":"px","dimension":{"top":"35","right":"30","bottom":"35","left":"30"}},"Mobile":{"unit":"px","dimension":{"top":"30","right":"30","bottom":"30","left":"30"}}},"containerPaddingHover":{"Desktop":[]},"containerBackground":{"type":"default","color":{"type":"variable","id":"white"}},"containerBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"30","right":"0","bottom":"0","left":"0"}},"Mobile":[]},"all":{"type":"none"},"bottom":{"type":"none","color":{"r":43,"g":123,"b":123,"a":1},"width":"8"}},"containerBoxShadow":{"horizontal":"0","vertical":"3","blur":"15","spread":"0","color":{"r":16,"g":16,"b":16,"a":0.1}},"containerBorderHover":{"radius":{"Desktop":[]}},"iconPadding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"iconMargin":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"15","left":""}}},"iconColor":{"type":"variable","id":"startupzy-primary"},"iconBgColor":{"r":254,"g":254,"b":254,"a":0},"iconBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"50","right":"50","bottom":"50","left":"50"}}}},"iconBorderHover":{"radius":{"Desktop":[]}},"titlePadding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":[]},"titleMargin":{"Desktop":[],"Mobile":[]},"titleColor":{"type":"variable","id":"startupzy-secondary"},"titleTypography":{"type":"variable","id":"gv-font-feature-secondary","font":{"label":"Helvetica","value":"Helvetica","type":"system"},"size":{"Desktop":{"unit":"px","point":"22"},"Mobile":{"unit":"px","point":"20"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.2"}},"weight":"600"},"descMargin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":[]},"descColor":{"type":"variable","id":"startupzy-bodytext"},"descTypography":{"type":"variable","id":"gv-font-text","font":{"label":"Heebo","value":"Heebo","type":"google"},"size":{"Desktop":{"unit":"px","point":"16"},"Mobile":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.7"}},"weight":"300"},"badgePadding":{"Desktop":[]},"badgeRadius":{"Desktop":[]},"parentSelector":".guten-tNYwfa:hover .guten-icon-box-wrapper","hasInnerBlocks":true,"imageLoad":"eager"} -->
<!-- wp:gutenverse/button {"elementId":"guten-pRMJOZ","buttonWidth":{"Desktop":""},"alignButton":{"Desktop":"center"},"paddingButton":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"buttonBackground":{"type":"default","color":{"r":217,"g":217,"b":217,"a":0}},"showIcon":true,"icon":"fas fa-arrow-alt-circle-right","iconSize":{"Desktop":{"point":"26","unit":"px"}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"20"}}},"padding":{"Desktop":[]},"iconColor":{"type":"variable","id":"startupzy-primary"},"parentSelector":".guten-tNYwfa:hover .guten-icon-box-wrapper"} /-->
<!-- /wp:gutenverse/icon-box -->
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":23,"Tablet":50},"elementId":"guten-PqwXja","margin":{"Desktop":[],"Mobile":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"","right":"0","bottom":"","left":""}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"animation":{"type":{"Desktop":"fadeInLeft"},"duration":"normal"}} -->
<!-- wp:gutenverse/icon-box {"elementId":"guten-Z3I65A","title":"Affordable Price","titleTag":"h3","description":"Lorem ipsum dolor sit amet, consectet adipiscing elit, sed do eiusmod tempor dolor","icon":"fas fa-money-check-alt","iconSize":{"Desktop":"40"},"iconPosition":"top","containerPadding":{"Desktop":{"unit":"px","dimension":{"top":"35","right":"30","bottom":"35","left":"30"}},"Mobile":{"unit":"px","dimension":{"top":"30","right":"30","bottom":"30","left":"30"}}},"containerPaddingHover":{"Desktop":[]},"containerBackground":{"type":"default","color":{"type":"variable","id":"white"}},"containerBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":[]},"all":{"type":"none"},"bottom":{"type":"none","color":{"r":43,"g":123,"b":123,"a":1},"width":"8"}},"containerBoxShadow":{"horizontal":"0","vertical":"3","blur":"15","spread":"0","color":{"r":16,"g":16,"b":16,"a":0.1}},"containerBorderHover":{"radius":{"Desktop":[]}},"iconPadding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"iconMargin":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"15","left":""}}},"iconColor":{"type":"variable","id":"startupzy-primary"},"iconBgColor":{"r":254,"g":254,"b":254,"a":0},"iconBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"50","right":"50","bottom":"50","left":"50"}}}},"iconBorderHover":{"radius":{"Desktop":[]}},"titlePadding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":[],"Tablet":[]},"titleMargin":{"Desktop":[],"Mobile":[]},"titleColor":{"type":"variable","id":"startupzy-secondary"},"titleTypography":{"type":"variable","id":"gv-font-feature-secondary","font":{"label":"Helvetica","value":"Helvetica","type":"system"},"size":{"Desktop":{"unit":"px","point":"22"},"Mobile":{"unit":"px","point":"20"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.2"}},"weight":"600"},"descMargin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":[],"Tablet":[]},"descColor":{"type":"variable","id":"startupzy-bodytext"},"descTypography":{"type":"variable","id":"gv-font-text","font":{"label":"Heebo","value":"Heebo","type":"google"},"size":{"Desktop":{"unit":"px","point":"16"},"Mobile":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.7"}},"weight":"300"},"parentSelector":".guten-Z3I65A:hover .guten-icon-box-wrapper","hasInnerBlocks":true,"imageLoad":"eager"} -->
<!-- wp:gutenverse/button {"elementId":"guten-WtVhJW","buttonWidth":{"Desktop":""},"alignButton":{"Desktop":"center"},"paddingButton":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"buttonBackground":{"type":"default","color":{"r":217,"g":217,"b":217,"a":0}},"showIcon":true,"icon":"fas fa-arrow-alt-circle-right","iconSize":{"Desktop":{"point":"26","unit":"px"}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"20"}}},"padding":{"Desktop":[]},"iconColor":{"type":"variable","id":"startupzy-primary"},"parentSelector":".guten-Z3I65A:hover .guten-icon-box-wrapper"} /-->
<!-- /wp:gutenverse/icon-box -->
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":23,"Tablet":50},"elementId":"guten-Zr3b6B","margin":{"Desktop":[],"Mobile":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Tablet":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"","right":"0","bottom":"","left":""}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":[]},"animation":{"type":{"Desktop":"fadeInLeft"},"duration":"normal"}} -->
<!-- wp:gutenverse/icon-box {"elementId":"guten-WuZ7nE","title":"24/7 Support","titleTag":"h3","description":"Lorem ipsum dolor sit amet, consectet adipiscing elit, sed do eiusmod tempor dolor","icon":"fas fa-user-check","iconSize":{"Desktop":"40"},"iconPosition":"top","containerPadding":{"Desktop":{"unit":"px","dimension":{"top":"35","right":"30","bottom":"35","left":"30"}},"Mobile":{"unit":"px","dimension":{"top":"30","right":"30","bottom":"30","left":"30"}},"Tablet":[]},"containerPaddingHover":{"Desktop":[]},"containerBackground":{"type":"default","color":{"type":"variable","id":"white"}},"containerBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"30","left":"0"}},"Mobile":[],"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"all":{"type":"none"},"bottom":{"type":"none","color":{"r":43,"g":123,"b":123,"a":1},"width":"8"}},"containerBoxShadow":{"horizontal":"0","vertical":"3","blur":"15","spread":"0","color":{"r":16,"g":16,"b":16,"a":0.1}},"containerBorderHover":{"radius":{"Desktop":[]}},"iconPadding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"iconMargin":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"15","left":""}}},"iconColor":{"type":"variable","id":"startupzy-primary"},"iconBgColor":{"r":254,"g":254,"b":254,"a":0},"iconBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"50","right":"50","bottom":"50","left":"50"}}}},"iconBorderHover":{"radius":{"Desktop":[]}},"titlePadding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":[]},"titleMargin":{"Desktop":[],"Mobile":[]},"titleColor":{"type":"variable","id":"startupzy-secondary"},"titleTypography":{"type":"variable","id":"gv-font-feature-secondary","font":{"label":"Helvetica","value":"Helvetica","type":"system"},"size":{"Desktop":{"unit":"px","point":"22"},"Mobile":{"unit":"px","point":"20"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.2"}},"weight":"600"},"descMargin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":[]},"descColor":{"type":"variable","id":"startupzy-bodytext"},"descTypography":{"type":"variable","id":"gv-font-text","font":{"label":"Heebo","value":"Heebo","type":"google"},"size":{"Desktop":{"unit":"px","point":"16"},"Mobile":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.7"}},"weight":"300"},"parentSelector":".guten-WuZ7nE:hover .guten-icon-box-wrapper","hasInnerBlocks":true,"imageLoad":"eager"} -->
<!-- wp:gutenverse/button {"elementId":"guten-ZHkkfd","buttonWidth":{"Desktop":""},"alignButton":{"Desktop":"center"},"paddingButton":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":[]},"buttonBackground":{"type":"default","color":{"r":217,"g":217,"b":217,"a":0}},"showIcon":true,"icon":"fas fa-arrow-alt-circle-right","iconSize":{"Desktop":{"point":"26","unit":"px"}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"20"}}},"padding":{"Desktop":[]},"iconColor":{"type":"variable","id":"startupzy-primary"},"parentSelector":".guten-WuZ7nE:hover .guten-icon-box-wrapper"} /-->
<!-- /wp:gutenverse/icon-box -->
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":31,"Tablet":50,"Mobile":null},"elementId":"guten-uGayZj","background":{"type":"default","color":{"type":"variable","id":"startupzy-primary"}},"border":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"30","bottom":"30"}},"Tablet":{"unit":"px","dimension":{"top":"0","bottom":"30"}}}},"margin":{"Desktop":{"unit":"px","dimension":{"left":"40"}},"Mobile":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"40","right":"40","bottom":"40","left":"40"}},"Mobile":{"unit":"px","dimension":{"top":"30","right":"30","bottom":"30","left":"30"}},"Tablet":{"unit":"px","dimension":{"top":"30","right":"30","bottom":"25","left":"30"}}},"animation":{"type":{"Desktop":"fadeInRight"},"duration":"normal"}} -->
<!-- wp:gutenverse/heading {"elementId":"guten-d04zkC","content":"Make Appointment","type":3,"textAlign":{"Mobile":"center"},"color":{"type":"variable","id":"white"},"typography":{"type":"variable","id":"gv-font-feature-secondary","font":{"label":"Helvetica","value":"Helvetica","type":"system"},"size":{"Desktop":{"unit":"px","point":"22"},"Mobile":{"unit":"px","point":"20"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.2"}},"weight":"600"},"containsAnchorTag":false,"border":{"radius":{"Tablet":[]}},"margin":{"Tablet":[]},"padding":{"Tablet":[]}} /-->

<!-- wp:gutenverse/text-editor {"elementId":"guten-2OYpNl","alignment":{"Mobile":"center"},"textColor":{"type":"variable","id":"white"},"typography":{"type":"variable","id":"gv-font-text","font":{"label":"Heebo","value":"Heebo","type":"google"},"size":{"Desktop":{"unit":"px","point":"16"},"Mobile":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.7"}},"weight":"300"},"containsAnchorTag":false} -->
<!-- wp:paragraph -->
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incidid </p>
<!-- /wp:paragraph -->
<!-- /wp:gutenverse/text-editor -->

<!-- wp:gutenverse/button {"elementId":"guten-RVDyDU","content":"Get Started","alignButton":{"Mobile":"center"},"paddingButton":{"Desktop":{"unit":"px","dimension":{"top":"20","right":"40","bottom":"20","left":"40"}},"Mobile":[]},"buttonBackground":{"type":"default","color":{"type":"variable","id":"white"}},"buttonBackgroundHover":{"type":"default","color":{"type":"variable","id":"startupzy-secondary"}},"buttonBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"20","right":"0","bottom":"20","left":"0"}}}},"buttonBorderHover":{"radius":{"Desktop":[]}},"showIcon":true,"icon":"fas fa-arrow-right","iconPosition":"after","iconSpacing":{"Desktop":"8"},"iconSize":{"Desktop":{"point":"13","unit":"px"}},"border":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"10"}}},"padding":{"Desktop":[]},"color":{"type":"variable","id":"startupzy-primary"},"iconColor":{"type":"variable","id":"startupzy-primary"},"typography":{"type":"variable","id":"gv-font-button-secondary","font":{"label":"Helvetica","value":"Helvetica","type":"system"},"size":{"Desktop":{"unit":"px","point":"13"}},"lineHeight":{"Desktop":{"unit":"em","point":"1"}},"spacing":{"Desktop":"0.15"},"transform":"uppercase","weight":"600"},"hoverIconColor":{"type":"variable","id":"white"},"hoverTextColor":{"type":"variable","id":"white"}} /-->
<!-- /wp:gutenverse/column -->
<!-- /wp:gutenverse/section -->
<!-- /wp:gutenverse/column -->
<!-- /wp:gutenverse/section -->',
	'is_sync' => false,
);
